name: Build Swagger Testing 2

on:
  push:
    branches:
      - master
    paths:
      - "swagger-testing-2/**"

env:
  PROJECT_ID: personal-project-2002
  IMAGE_NAME: gcr.io/personal-project-2002/swagger-testing-2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v3"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Submit Build to Cloud Build
        run: |
          gcloud builds submit \
            --tag ${{ env.IMAGE_NAME }}:latest \
            ./swagger-testing-2
